server {
    listen 80;

    # Блокуємо зовнішній доступ до health-чеків
    location /health/ {
        return 404;
    }

    # Перевірка Accept для кореня
    location = / {
        if ($http_accept ~* "text/html") {
            return 406;
        }
        proxy_pass http://app:8000;
        proxy_set_header Host $host;
    }

    # Усі інші запити (наприклад, /items)
    location / {
        proxy_pass http://app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}